### ISSUE TITLE
建议：需要补充自述文件

### ISSUE THREAD

**Issue by xiwangly2** [1250422131/LastOrderBot#1]
请补充此项目的自述文件，它应该包含如何安装/卸载等信息，例如链接到[B站机器人搭建 LastOrderBot](https://imcys.com/2021/02/19/b%e7%ab%99%e6%9c%ba%e5%99%a8%e4%ba%ba%e6%90%ad%e5%bb%ba-lastorderbot.html)

**Comment by 1250422131** [comment]
了解，目前已经完成了基本信息的补充

**Comment by xiwangly2** [comment]
Thinks.
